export default {
  YELP_CONSUMER_KEY: 'TMXpPB0Cfc1STQaeBf6wKQ',
  YELP_CONSUMER_SECRET: 'NnxsLL9_Kel_Ls0mImLOQXHaMuk',
  YELP_TOKEN: 'CqzYbfwlIM1m_N-YE3Urj0D1fDexctdw',
  YELP_TOKEN_SECRET: 'PME0iUho7N-bLpt7G2MBZ6UdrVI'
};
