export default {
  YELP_CONSUMER_KEY: 'lFk9sIX33O4ny4pc7kub8g',
  YELP_CONSUMER_SECRET: 'ZUGN4VG9nnJynqv_eWn88opKdJM',
  YELP_TOKEN: 'FR44XcASiDCc3vG1znvULHyRuBHBlRRa',
  YELP_TOKEN_SECRET: 'r5Hxr2E8zNeSxhJoQmqrvKCM9Qk'
};
